spring:
  application:
    name: gateway-app

  cloud:
    gateway:
      routes:

        - id: send_message
          uri: http://localhost:8082
          predicates:
            - Path=/v1/producer
            - Method=POST

eureka:
  client:
    instance:
      hostname: localhost
    registerWithEureka: true
    fetchRegistry: true
    serverviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health, info
        exclude: env,beans
    prometheus:
      enabled: true
  metrics:
    export: 
      prometheus: 
        enabled: true