version: '3'
services:
  
  mongodb: 
    container_name: mongodb 
    image: mongo 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.21
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports: 
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  prometheus: 
    container_name: prometheus
    image: prom/prometheus
    ports: 
      - "9090:9090"
    volumes:
      - prometheus:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    

volumes:
  prometheus:
    