global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: consumer
    metrics_path: '/actuator/health'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8081']
  - job_name: producer
    metrics_path: '/actuator/health'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8082']
  - job_name: gateway
    metrics_path: '/actuator/health'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
  - job_name: eureka
    metrics_path: '/actuator/health'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8761']
  - job_name: configserver
    metrics_path: '/actuator/health'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8888']