#spring:
#  application:
#    name: gateway-app
#
##  gateway:
##    routes:
##      - id:
##        uri:
##        predicates:
##          - Path=
##          - Methods=
#
#eureka:
#  client:
#    instance:
#      hostname: localhost
#    registerWithEureka: true
#    fetchRegistry: true
#    serverviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#server:
#  port: 8080
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: metrics, prometheus, health